### ISSUE TITLE
Add filter to srcset array in  tevkori_get_srcset_array

### ISSUE THREAD

**Issue by orionrush** [ResponsiveImagesCG/wp-tevko-responsive-images#108]
Related to, but different enough from https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/101 to not piggyback. 

At present for template images I detect the presence of 2x images via `file_exsists` and if present add them to the srcset attribute through the $atts param array in `wp_get_attachment_image()`.

[full gist here] (https://gist.github.com/961f0dc20a831ed5cc06.git)

I believe a filter on the output of  `tevkori_get_srcset_array()` make theses new 2x items available to the following as well:

    tevkori_get_srcset
    tevkori_get_srcset_string
    tevkori_get_src_sizes
    tevkori_extend_image_tag (which image_send_to_editor)

This would provide a means of including these 2x images for `image_send_to_editor` as well, though I dont think it would directly help our friend @solemone: https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/98. For this `tevkori_extend_image_tag` would also need a filter.

Looking through `wp-tevko-responsive-image.php` I could see scope for people wanting to control the output for most of the functions I've listed, and more. Is there any reason not to add these?

Another compelling use case is the [Retna x2 plugin](https://wordpress.org/plugins/wp-retina-2x/) which has recently released a mini api for its image creation gui of x2 images.

**Comment by jiwicky** [comment]
This would be super helpful to filter out unneeded sizes in srceset and only use the breakpoint images. I'm running into issues with this in a theme I'm developing where I have added a bunch of image sizes for other reasons but only want to use 3 of them for the_post_thumbnails. Unless there is already a way to do this, but I don't see a good way. 

Anyhow, would be really great to add some hooks to this bad ass plugin!

**Comment by jiwicky** [comment]
... could be done as an apply_filters to $arr in tevkori_get_srcset_array() I think.
