### ISSUE TITLE
Advanced image compression only outputting one source

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/wp-tevko-responsive-images#116]
Chucked together a bone stock WP install (apart from one plugin to knock out Emojis, due to https://wordpress.org/support/topic/version-422-wp-emoji-releaseminjs-error) for testing 2.3, with advanced image compression toggled on.

Talked it through a little with @tevko, and it looks like advanced image compression is causing only a single source to be generated; see http://www.wp-test.matmarquis.com/2015/05/18/ricgwp-2-3/ 

Disable advanced image compression and everything goes back to normal.

**Comment by nwtn** [comment]
@Wilto Crazy request, but can you see if the same thing happens with a JPEG?

**Comment by joemcgill** [comment]
I just spun up a brand new site, turned on the the plugin, added support for advanced image compression, and uploaded a PNG (just to be sure) and got all the crops I was expecting. Can we find out what version of Imagemagick is installed on your test site as well?

**Comment by Wilto** [comment]
@nwtn
Same deal: 

```html
<img class="alignnone size-full wp-image-24" 
    src="http://www.wp-test.matmarquis.com/wp-content/uploads/2015/05/whm.jpg" 
    srcset="http://www.wp-test.matmarquis.com/wp-content/uploads/2015/05/whm.jpg 900w" 
    alt="whm"
    width="900" height="600" 
    sizes="(max-width: 900px) 100vw, 900px">
```
http://www.wp-test.matmarquis.com/2015/05/18/ricgwp-2-3/

@joemcgill

```shell
Version: ImageMagick 6.6.9-7 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP
```

**Comment by joemcgill** [comment]
@nwtn You may want to take a look at the last comments on #132. Seems like a similar issue.

**Comment by joemcgill** [comment]
Going to close this in favor of #150, which I believe rightly identifies the issue as a memory limit issue. We can keep the discussion going on that ticket.
