### ISSUE TITLE
[Req] Do not do anything if there are only one image size available

### ISSUE THREAD

**Issue by Profforgr** [ResponsiveImagesCG/wp-tevko-responsive-images#121]
Hi.

I have found out that for some reason there are only one image size available for most (actually all in my case, but i did not make full search, just fast overview). And this plugin simply add's more content to HTML which is useless.

I think it would be better just do nothing if there are only 1 image size available.

**Comment by nwtn** [comment]
Are you using the advanced image compression feature? If so, does turning it off resolve the problem?

**Comment by Profforgr** [comment]
> Are you using the advanced image compression feature? If so, does turning it off resolve the problem?

Nope. Just installed plugin and nothing else.

**Comment by joemcgill** [comment]
This is a good suggestion. If we only have one source candidate, we just return the original HTML instead of adding `srcset` and `sizes`. I can work up a patch unless someone else has an interest.

**Comment by jhned** [comment]
I could work up a patch by this evening, if you like.

**Comment by joemcgill** [comment]
@jhned go for it.

**Comment by tevko** [comment]
Closed in https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/154
