### ISSUE TITLE
Thumbnails not generating with RICG enabled.

### ISSUE THREAD

**Issue by justincavery** [ResponsiveImagesCG/wp-tevko-responsive-images#132]
I've been running a local copy and live site using WP Migrate Pro to pull the updates down to local.

Both had RICG installed and the local copy creates image size varieties, but the live site does not create them. Even using Regenerate Thumbnails it wouldn't work.

The database was the same, as was all of the theme files so I can't work out what might be wrong.

Let me know what you need for a better issue log.

**Comment by joemcgill** [comment]
Interesting. Are you using the advanced image compression option or is it just a standard install? If you are, does the issue remain if you turn that option off?

**Comment by justincavery** [comment]
I was using the advanced image compression on both (functions.php was copied across from local to live). It worked on the local but on the remote it was failing.

I disabled the AIC in the functions.php but it didn't fix the problem on the live/remote server.

**Comment by joemcgill** [comment]
If turning off the advanced image compression settings had no affect, then I would suspect there may be something wrong with the setup of the live server. If you disable the plugin entirely on the live server, do the thumbnails get created or is it still broken? If the later, you may not have Imagemagick or GD installed on the server at all.

**Comment by justincavery** [comment]
Disabling the plugin on the live server allowed the images to be created again.

I've fallen back to only specifying key areas (templated areas) with manual srcset and sizes declarations and leaving the plugin disabled, but it would be great to enable it for the continued news posting.

**Comment by joemcgill** [comment]
It's odd that the plugin is affecting the creation of images when you've disabled the advanced image compression feature. Maybe @nwtn would have some ideas here. Just for fun, could you try enabling the plugin without the advanced image compression setting enabled (i.e., the default setup), and compare that against the plugin with these lines commented out in `wp-tevko-responsive-images.php`:

```
require_once plugin_dir_path( __FILE__ ) . 'class-respimg.php';
require_once plugin_dir_path( __FILE__ ) . 'class-wp-image-editor-respimg.php';
```

If that still doesn't fix the problem, then try the plugin on a default theme with no other plugins activated, just to make sure there's not something else conflicting.

**Comment by justincavery** [comment]
I'm going to hold off of testing anything more for a few weeks as the project will go live in the next few days. I'll get back to you with the results soon.

**Comment by joemcgill** [comment]
Thanks @justincavery.

**Comment by isaiahmg** [comment]
Hey Joe! It was great meeting you at WCDenver this weekend. I just noticed this same issue as well--advanced image compression working on my local machine but not on production. I haven't investigated this issue much yet, but we're using WP Engine for hosting, and so perhaps their setup doesn't support certain features needed by the advanced image compression.

**Comment by joemcgill** [comment]
Thanks for the report @isaiahmg. It was nice meeting you as well. In your case, if the images are being generated when the plugin is activated but the advanced compression is turned off, then it's probably related to #116. It's possible that the issue @justincavery has reported is the same, but I want to make sure we don't have two separate issues here, one with the plugin activated + image compression and a separate that affects the site _any_ time the plugin is active.

**Comment by isaiahmg** [comment]
Hey @joemcgill. I think what I was experiencing was similar to #116. When I ran the Regenerate Thumbnails plugin on the WP Engine I was left only with a single image (which may mean it wasn't processed at all). You can see WP Engine's phpinfo, here: http://phpinfo.wpengine.com/info.php#module_imagick

The PHP version on my local machine is 5.6.2 and I don't find anything about ImageMagick when I run phpinfo. Perhaps it uses GD in that case? My gd version is "2.1.0 compatible."

**Comment by joemcgill** [comment]
Thanks @isaiahmg, very helpful.

**Comment by joemcgill** [comment]
Going to close this in favor of #150, which I believe rightly identifies the issue as a memory limit issue. We can keep the discussion going on that ticket.
