### ISSUE TITLE
Generated image (via add_image_size) with same proportion as the original image

### ISSUE THREAD

**Issue by daviedR** [ResponsiveImagesCG/wp-tevko-responsive-images#141]
Hey,

I want to report an important bug.

My theme has 2 columns layout (main & sidebar). Sidebar has 300px width. For that purpose, I created a new custom image size, named "sidebar-thumbnail", with 300x200px hard crop sized.

On my sidebar, there is a custom widget, which lists posts along with the thumbnail image (300x200). My original uploaded images are always in 900x600px. WordPress will automatically generate the 300x200px version by itself.

When the plugin is activated, my sidebar now use 900x600px image thumbnail instead of the 300x200px. This is because the additional image size (300x200) has the same proportion as the original image size (900x600px).

Your plugin detects the same size ratio, and put the "srcset" attribute, which makes all images on the sidebar loads the 900x600px image (original version) instead of the 300x200px image (meant to be thumbnail for sidebar).

This is not a good result, because sidebar needs small thumbnail not the original size, which will slow down the page load time.

**Comment by jaspermdegroot** [comment]
@daviedR 

Can you copy the markup of one of your sidebar images and paste it in a comment here so we can take a look at the generated ```sizes``` attribute?
Does the device on which you notice this have a HD screen or not? If it's HD 900x600px might be the right image to load.
Thanks!

**Comment by tevko** [comment]
Closing due to lack of response - feel free to continue commenting on this thread
