### ISSUE TITLE
Custom breakpoints?

### ISSUE THREAD

**Issue by ethanclevenger91** [ResponsiveImagesCG/wp-tevko-responsive-images#142]
Correct me if I'm wrong, but the plugin currently generated srcset and the associated breakpoints based on the defined image sizes. What if I wanted to overwrite this and pass my own breakpoints with their associated image sizes? Does this currently support something like this?

**Comment by tevko** [comment]
If I'm understanding the issue correctly, you can do this by setting custom image sizes in the wordpress admin. Then, you can create a hook which modifies the sizes attribute in functions.php. More info on that here - https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/tree/master#tevkori_get_sizes-id-size-args-

**Comment by ethanclevenger91** [comment]
Ah, didn't realize I could pass it args. Excellent. One more question if you don't mind - can I turn it off by default? I'm a theme developer and would like to pick and choose when it gets used, or at least prevent it from using certain image sizes so I don't have to pass my own args based on the context every time.

**Comment by tevko** [comment]
I think this might be what you're looking for - https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images#tevkori_get_srcset_array-id-size-

**Comment by ethanclevenger91** [comment]
Okay I actually misunderstood the first link you sent me, and this may be a shortcoming of image srcsets as a whole. While I realize putting media queries in markup isn't ideal, with the picture element, I can say "Default, use this image. Within this media query, use this image." And so on.

The image element, by contrast, just picks the biggest one that is still smaller than the viewport, and there isn't really a way to overwrite that - you can just pass it information about your images. Or am I misunderstanding that?

**Comment by tevko** [comment]
Sorry to be continuously throwing links at you! The original version of this plugin, before it was forked, was using the picture element. This CSS-Tricks article explains the srcset attribute and why it's a better fix - https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/

**Comment by ethanclevenger91** [comment]
So if I'm understanding this right, I want to put my media queries into my `sizes`

**Comment by tevko** [comment]
Yes! But it does it better and with less code, because it determines the best image to use based on screen size AND DPI

**Comment by ethanclevenger91** [comment]
Awesome, I feel like that isn't said quite so clearly anywhere or with diagrams. That's all I had - questions. You can close this up. Thanks a lot!

**Comment by tevko** [comment]
No problem, glad to help!
