### ISSUE TITLE
Add WP-CLI command for rewriting old posts

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#143]
Another approach to providing responsive images to posts written prior to installing this plugin, is to provide a command through WP-CLI which would update all of the posts in the database with the new image markup. Ideally, we would do a search of the DB for all instances of images with a URL path that matches the site's uploads directory (or by looking for a `wp-image-` class) and update each of those posts so that they can be rolled back, via post revisions, if anything breaks.

**Comment by joemcgill** [comment]
Related to issue #83

**Comment by jiwicky** [comment]
+1

**Comment by ryanwiemer** [comment]
+1 I really hope this can be implemented in the near future.

**Comment by jasperf** [comment]
+1 Would really be great. Just added the plugin and the blog is atm loading several older posts that do not have the images that are responsive.

**Comment by joemcgill** [comment]
Since we've switched to a display filter, this functionality is no longer needed. Related #148.
