### ISSUE TITLE
Why is the picturefill-Script in the footer?

### ISSUE THREAD

**Issue by benjaminpick** [ResponsiveImagesCG/wp-tevko-responsive-images#147]
As I read the documentation of the picturefill.js, they recommend to insert it into the head section. Do you have a specific reason not to do it? 

I have disabled it for now in my theme:
```php
  wp_register_script('picturefill', get_template_directory_uri() . '/assets/js/picturefill.min.js', false, null, false);
   remove_action( 'wp_enqueue_scripts', 'tevkori_get_picturefill' );
```

and indeed, images load much faster in Safari. (I've also followed the recommondation that the img-tags should not have an src value, so no image is loaded until picturefill kicks in, which leaves the site in a rather bad shape.)

**Comment by jaspermdegroot** [comment]
@benjaminpick - See https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/36#issuecomment-72076583

@joemcgill @tevko - Can you close this ticket? Thanks!
