### ISSUE TITLE
How should the sizes attribute be handled?

### ISSUE THREAD

**Issue by jhned** [ResponsiveImagesCG/wp-tevko-responsive-images#15]
We ought to be able to set a default `sizes` attribute without having to insert it into every image manually. That way the default `sizes` string could be pulled in dynamically for all images without having to edit any posts/pages/etc.

However, that quickly falls apart once you have images for different purposes. Images in the content area will probably need a different `sizes` attribute than post thumbnails. 

To solve that issue, we could define image groups in the WordPress admin, rather than image sizes alone. Image groups would consist of at least 2 image sizes, and a `sizes` string. For example:

1. Image Size 1 is 4:3, set to a hard crop at 320px by 240px, takes up 100% of the viewport width on mobile.
2. Image Size 2 is 3:2, set to a hard crop at 540px by 360px, takes up 50% of the viewport width at a browser width of 1080px.

So, a hypothetical `sizes` attribute for this image group would be `sizes="(max-width: 320px) 100vw, 50vw"` or `sizes="(min-width: 1080px) 50vw, 100vw"`, depending on your priorities.

**Comment by joemcgill** [comment]
Since the use case for `sizes` is dependent on the the desired layout of the page, it seems to me that the it may be best to handle sizes by extending the template tag. I would imagine something like:

```
tevkori_get_src_sizes( $id, $size, $args );
```

where `$id` would be the image id, $size would be the main image size to return, and `$args` could be used to pass an array of sizes (or other attributes) which could be used to build the desired output.

**Comment by tevko** [comment]
@joemcgill @jhned the first 2 attributes exist already, but $args does not. As for the sizes attribute, I think that might be best left to the theme developer to handle

**Comment by tevko** [comment]
@joemcgill @jhned the goal of this plugin is to provide seamless default functionality, which I think we're doing pretty well. I'm not sure if like to introduce any sort of admin functionality to this plugin. WordPress is customizable, and it's probably best for theme developers to handle something that only they would know the requirements for

**Comment by joemcgill** [comment]
I tend to agree. If we were going to handle anything beyond native src
switching in core, which I'm not sure we should, I think template tags are
the best way to go.

**Comment by jhned** [comment]
@tevko, sure, there's certainly more than one way to implement `sizes` into the plugin, but I'd say that the plugin needs support for `sizes` in some fashion, even if it's just an optional argument in the `tevkori_get_src_sizes` function. That would give us support for `sizes If this is to be a responsive images plugin, why would we include support for `srcset` and not `sizes` as well?

**Comment by joemcgill** [comment]
@jhned the issue with providing `sizes` support to content images, is that it requires knowledge about the layout of the content, which is something best left to theme authors to provide. As @tevko pointed out, the main purpose of this plugin is to bring seamless responsive functionality (even if only partial functionality) into WordPress core, so the scope may end up needing to be narrower than a plugin that would add support for all the responsive image techniques, many of which may be best left to theme and plugin authors to execute.

**Comment by jhned** [comment]
@joemcgill I agree that we should not make assumptions about what the value of the sizes attribute would be. I'm just saying that it could be beneficial if we gave theme and plugin authors a function, filter, or variable to hook into, rather than forcing each individual author to come up with their own solution. But if that's not within the scope of this plugin, I understand.

**Comment by timrourke** [comment]
Is there any potential conflict with the hardcoded image sizes that the plugin adds and existing image sizes previously defined in the theme? I see the wisdom of adding a set of sane values for image sizes for the average use case, like 320, 640, 960, 1280, as the plugin does, but if someone already has exactly those values defined, is there risk in duplication?

**Comment by tevko** [comment]
@timrourke see https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/13

**Comment by timrourke** [comment]
Ah, duh. Thanks!

**Comment by tevko** [comment]
@jhned I think that providing a hook, filter, or additional function parameter for the sizes attribute would actually be more complicated than letting the theme developer handle sizes on their own

**Comment by jhned** [comment]
@tevko, well here's another thought: what if you have an image that's 16:9 on desktop, but you want it to be 3:2 on mobile? According to the way the plugin is set up now, if you insert the 16:9 image size, only other 16:9 image sizes will be included in the `srcset` attribute. 

This is why I think that image groups would be a good idea. Theme authors could define them like this:

`add_image_group(‘content_images’, array(‘small-square-size’, ‘rectangle-medium-size’, ‘widescreen-large-size’);`

Then all we'd have to do is include the Image Group Name ("Content Images," in this example) in the Image Size dropdown in the Add Media dialog, and the `tevkori_get_src_sizes` function would only use the image sizes in the group.

The registered image group could also include a parameter for the `sizes` attribute. So you'd be solving two issues. Image groups give developers:

1. A way to manually specify which image sizes to include in the `srcset` attribute.
2. What the `sizes` attribute should be.

If this plugin is going to eventually go in to Core, those two issues are going to come up again. Without a method to solve both those problems, the out-of-the-box responsive images solution will be incomplete and frustrating for most professional developers.

**Comment by tevko** [comment]
@jhned You've outlined several issues that, while all plausible, go outside of the scope of this plugin. 

This plugin, and if I may be so bold, all of WordPress, is not designed to be a comprehensive solution to any and all possible problem that a theme developer may come up against. Rather, it is our goal to provide the most basic functionality needed to include responsive images on a WordPress site. Anything outside of that is left up to the theme developer, as it should be. 

Switching resolutions was the goal, and we've accomplished that. Switching dimensions is a much more involved and less occurring problem. As previously stated, our goal is to allow for basic resolution switching without the need for a settings page or extra  media uploader options.

I would have to argue that if this plugin is going to core, it needs to be as simple as possible, while still solving a general problem. So far I think it does that very well. It was never intended to be an out of the box comprehensive responsive images solution. Instead, its meant to give users a much needed feature (basic resolution switching) while enabling them to add to it as needed (for issues like dimension switching and sizes attribute).

**Comment by jhned** [comment]
I would agree with you that any plugin that goes to core needs to be as simple as possible. But I would also argue that it needs to be as bulletproof as possible, so that it doesn't introduce undesired behavior. At the very least, core code often includes action and filter hooks, so that developers can manipulate the output when necessary.

I understand that what I've suggested is outside the scope of this plugin, so I'll go ahead and close the issue.

**Comment by joemcgill** [comment]
@jhned thanks for raising this issue. We may very well need to revisit it at some point in the future and this conversation will be helpful when it comes up again (which I'm sure it will). 

I would just like to add that, at this point, the plugin functions as a filter to add the `srcset` attributes to an `img` element. In doing so, there's nothing to keep developers from adding additional filters which give them the desired output for defining custom size attributes, or even creating custom template tags for outputting full `picture` elements in their themes (which I have done several times, btw).

**Comment by joemcgill** [comment]
Related #21
