### ISSUE TITLE
Warning in media page for svg image

### ISSUE THREAD

**Issue by grappler** [ResponsiveImagesCG/wp-tevko-responsive-images#153]
I get the following warnings on the media page(wp-admin/upload.php) for svg images that I have uploaded

```
Warning: Illegal string offset 'sizes' in plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 165

Warning: Illegal string offset 'width' in plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 169

Warning: Illegal string offset 'height' in plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 170

Warning: Illegal string offset 'file' in ricg-responsive-images/wp-tevko-responsive-images.php on line 171

Warning: Illegal string offset 'file' inplugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 173
```

**Comment by jaspermdegroot** [comment]
@grappler 

Without knowing what plugin or custom code you use to add support for SVG (WordPress itself doesn't support SVG) I can't test it, but I am pretty sure that commit https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/c463c9060b3318e775ca90efb2c893abc5ca6814 will fix your problem. That change will be part of the next release of this plugin.

**Comment by grappler** [comment]
The code that I am using is:
```php
/**
 * Allow SVG to be uploaded
 */
function wpzoo_svgs_upload_mimes( $mimes ) {

	if( current_user_can( 'administrator' ) ) {
		$mimes['svg'] = 'image/svg+xml';
	}

	return $mimes;
}
add_filter( 'upload_mimes', 'wpzoo_svgs_upload_mimes' );
```

I tested the commit and it fixes the issue.

When do you plan to release the next update?

**Comment by jaspermdegroot** [comment]
@grappler - We plan on a release by the end of this week
