### ISSUE TITLE
Add shortcode for use in WordPress editor

### ISSUE THREAD

**Issue by cferdinandi** [ResponsiveImagesCG/wp-tevko-responsive-images#16]
Currently, because this plugin requires PHP to use, it cannot be used in the WordPress editor. Example:

```html
<img src="myimg.png" <?php echo tevkori_get_src_sizes( 11, 'tevkoriMedium-img' ); ?> />
```

This won't work in the WP editor. Adding a shortcode reference for `tevkori_get_src_sizes` will allow it to be used in the editor as well. Example:

```html
<img src="myimg.png" [tevkori_get_src_sizes id="11" size="'tevkoriMedium-img"] />
```

Thanks!

**Comment by jhned** [comment]
A `srcset` string is generated when using the Add Media button to insert an image into the Editor. In what use cases would a shortcode be more beneficial than the generated `srcset` string?

**Comment by tevko** [comment]
I have to agree with Josh on this one, unless I'm misunderstanding the
issue, this plugin has been specifically developed to work in the Editor

**Comment by cferdinandi** [comment]
Looks like I read the documentation incorrectly. I thought hardcoding was the only option. I see now. Closing out the ticket. Apologies!
