### ISSUE TITLE
Image fail upload. 'HTTP Error.'

### ISSUE THREAD

**Issue by Taylor4484** [ResponsiveImagesCG/wp-tevko-responsive-images#167]
I've got the plugin installed. It seems that images generated from photoshop can cause uploads to fail with a simple 'HTTP Error'. 

Disabling the RRIG plugin fixes the issue. It's not all images though. This affects uploads directly to the media page as well as via the media adder in posts and pages. I can upload non-Photoshop generated images just fine. 

I'm able to reproduce on multipule different WordPress instances. 

Here's the image I'm struggling to upload: 
https://s3.amazonaws.com/uploads.hipchat.com/16076/1241494/7Z0uil2VORNx8gQ/Ageing%20Workforce-1.jpg

Here's the JS errors that are generated when that upload fails after struggling for a few minutes: 
```mysite.com/wp-admin/async-upload.php Failed to load resource: the server responded with a status of 502 (Bad Gateway)```

```mysite.com/wp-admin/admin-ajax.php Failed to load resource: the server responded with a status of 502 (Bad Gateway)```

Image of error:
https://s3.amazonaws.com/uploads.hipchat.com/16076/1241494/1EiFAzOJytteAis/Screen%20Shot%202015-09-02%20at%2011.20.33%20AM.png

**Comment by joemcgill** [comment]
Hi @Taylor4484. Try turning of the advanced image compression option and see if that resolves the issue. You're probably experiencing #150.

**Comment by Taylor4484** [comment]
I can confirm that disabling advanced image compression does resolve the issue! Thanks @joemcgill 

We're good to close this issue unless the details here help #150

**Comment by joemcgill** [comment]
Thanks for confirming @Taylor4484. I'll go ahead and close this one and it'll be tracked over there.

**Comment by clicknathan** [comment]
Where exactly does one turn advanced image compression off?

Using something like this:

function custom_theme_setup() {
    remove_theme_support( 'advanced-image-compression' );
}
add_action( 'after_setup_theme', 'custom_theme_setup' );

Or is there a hidden settings page somewhere?

**Comment by joemcgill** [comment]
@clicknathan the advanced image compression feature is not on by default, you have to turn it on through and `add_theme_support()` flag in your theme. See: https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images#advanced-image-compression
