### ISSUE TITLE
Jetpack's Photon module

### ISSUE THREAD

**Issue by ChrisBegley** [ResponsiveImagesCG/wp-tevko-responsive-images#169]
I was just testing this out and noticed that if Jetpack's Photon module is activated, the plugin doesn't work. If I disable Photon, then I see the srcset and sizes attributes added to the featured images as expected.

**Comment by joemcgill** [comment]
Hi @ChrisBegley, this is the expected behavior since Photon is dynamically serving scaled versions of your images, so the `srcset` attribute is unnecessary. See #46

**Comment by ChrisBegley** [comment]
Hey @joemcgill,
Photon uses javascript to do that, which causes multiple versions of an image to be downloaded (first the original size, then the scaled version). It'd be nice to get native srcset support to avoid the extra bandwidth needed with the current Photon solution. Is this something I should bring up with the Jetpack team? I know that this plugin may make it into WordPress 4.4, so it'd be cool if it played nicely with Jetpack and Photon.
