### ISSUE TITLE
Ok to turn off Linthub?

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#174]
Not sure how Linthub checks got added to the plugin, but they were always failing since the PHP coding standards it was using didn't match WP coding standards. If we find a way to automatically lint using WP's standards, we can turn this back on.

**Comment by jaspermdegroot** [comment]
We can fix this by adding a .linthub.yml config file to the repo. In there we can point at a ruleset.xml file that contains the configuration for php linting. There are ruleset.xml files out in the open that are based on the WordPress coding standards.

When I did a search for existing WordPress config files I ended up in one of @peterwilsoncc his repos: https://github.com/peterwilsoncc/rapid-comment-reply/commit/3a1779c9213c852b6ac69825f7aee4a14e7e9787

**Comment by peterwilsoncc** [comment]
I borrowed these from another repo myself. `.jshint` comes from the wordpress-devel repo. I can't remember where I got the php config from, I'm afraid.

**Comment by jaspermdegroot** [comment]
@joemcgill I will create a PR to add Linthub config.

**Comment by jaspermdegroot** [comment]
@joemcgill 

I just noticed that there are two Linthub webhooks now (https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/settings/hooks). There was only one two days ago and I don't see any difference between the two. It also looks like the hook isn't working at the moment.
I am going to delete one of the hooks. Sorry if I break something ;)

**Comment by joemcgill** [comment]
No problem. I think it was me who added the second while trying to test the
patch. I can fix it.

**Comment by jaspermdegroot** [comment]
Turned out that the Linthub webhook that remained after I deleted one was inactive. I just activated it again and it should be working now.
