### ISSUE TITLE
Support older versions of WordPress?

### ISSUE THREAD

**Issue by mdmcginn** [ResponsiveImagesCG/wp-tevko-responsive-images#18]
The plugin isn't working on my new site, which uses WordPress 3.9.2 and Canvas/Woo Themes. Would it be hard to support older versions of WordPress? Should we try? If we did, would we be encouraging people to run older, insecure versions of WordPress?

**Comment by tevko** [comment]
There could be a few reasons that this isn't working on your site. Are you seeing any specific error messages? Can you post the resulting image markup after grabbing an image using the wordpress editor?

**Comment by jhned** [comment]
Just a stab in the dark, but tinyMCE might be stripping the srcset for older versions of WordPress, I know they only just fixed that bug in 4.1.

**Comment by tevko** [comment]
I know of that issue, but you would still get something on the front end
even though that's occuring

**Comment by tevko** [comment]
@jhned that's more than likely what's causing it

**Comment by tevko** [comment]
I implemented a fix before being told that 4.1 would finally address the issue - https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/89a45261fcb4e21dc0fb59096f68bf4ef0c9abd6

**Comment by mdmcginn** [comment]
tinyMCE is likely my problem. The resulting image markup has no srcset. I don't see any error messages.

**Comment by tevko** [comment]
So then a (possibly hackey) fix would be to add this to your functions.php file https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/89a45261fcb4e21dc0fb59096f68bf4ef0c9abd6 

as far as supporting older versions of WP, I think it's best to encourage users to update

**Comment by mdmcginn** [comment]
After adding the fix, I got `Fatal error: Cannot redeclare override_mce_options() (previously declared in /srv/www/vhosts/dmc-wp/wp-content/themes/tamutoday/functions.php:20) in /srv/www/vhosts/dmc-wp/wp-content/plugins/respimg/wp-tevko-responsive-images.php on line 44`

**Comment by tevko** [comment]
then in your themes functions.php file, around line 20, make sure that the ``override_mce_options()`` function includes the same parameters that exist in https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/89a45261fcb4e21dc0fb59096f68bf4ef0c9abd6

**Comment by mdmcginn** [comment]
Error because I'm using an earlier version of the plugin which already contained 89a4526. 

Okay. It's legitimate to tell people "Upgrade if you want it to work".
