### ISSUE TITLE
PF 2.2.0 or PF 2.2.2?

### ISSUE THREAD

**Issue by AlchemyUnited** [ResponsiveImagesCG/wp-tevko-responsive-images#19]
The change log sez 2.2.2 but the actually repo is 2.2.0.

**Comment by tevko** [comment]
Could you be a little bit more specific on the exact nature of the issue

**Comment by janhenckens** [comment]
I think @AlchemyUnited means that the readme says the plugin uses "Uses Picturefill 2.2.2 (Beta)", while the files in /js all have "v2.2.0-beta" in the header.

**Comment by AlchemyUnited** [comment]
@janhenckens - yup. that's it. thank you.
