### ISSUE TITLE
Make 'medium' the default size in internal functions instead of 'thumbnail'?

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#192]
Several of our internal function are using 'thumbnail' as the default size parameter. Since the 'thumbnail' size is usually a hard crop and is less likely to result in a `srcset`, should we switch that default to use the 'medium' size?

**Comment by peterwilsoncc** [comment]
* `wp_get_attachment_image` and `wp_get_attachment_image_src` default to thumbnail
* `wp_get_attachment_link` defaults to medium

Core is already inconsistent, medium makes sense to me.

**Comment by tevko** [comment]
:+1:

**Comment by jaspermdegroot** [comment]
:+1:
