### ISSUE TITLE
image url in srcset for media library is wrong

### ISSUE THREAD

**Issue by tkellen** [ResponsiveImagesCG/wp-tevko-responsive-images#209]
This does not work:
https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/blob/dev/wp-tevko-responsive-images.php#L202-L204

...if you are using this plugin:
https://wordpress.org/plugins/amazon-s3-and-cloudfront/

**Comment by jaspermdegroot** [comment]
@tkellen 

Thanks for reporting the issue. There is already a ticket for this and we are discussing how to deal with this. See https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/190.
I am closing this ticket as duplicate.

**Comment by tkellen** [comment]
Thanks!
