### ISSUE TITLE
The Plugin displays bigger image sizes than the max-width of the Theme

### ISSUE THREAD

**Issue by FlorianBrinkmann** [ResponsiveImagesCG/wp-tevko-responsive-images#21]
Hi,

at first: Thanks for your work on this plugin, it`s great! :)

I tried it on my blog and it works very fine. But when the viewport is wider than an uploaded full width image (for exapmle 1200px) then the plugin loads this image and the theme scales it down.

You can see it here (for example the featured image for the "the_posts_pagination"-post): http://brinkmannblog.de/

I hope it was understandable :)

Florian

**Comment by tevko** [comment]
hey @FlorianBrinkmann , I'm having a hard time finding an image that has a srcset attribute. Can you be a little bit more specific on where I can find a place on your site that's using this plugin?

**Comment by FlorianBrinkmann** [comment]
hi @tevko, of course, sorry. The attached image on the homepage is a featured image and uses the plugin.

![wordpress-4-1-paginierte-navigation-erstellen-featured](https://cloud.githubusercontent.com/assets/2310924/5859144/5acdaaf6-a258-11e4-90d2-d522b0a62c98.jpg)

![responsive-images-wordpress-problem](https://cloud.githubusercontent.com/assets/2310924/5859181/a42bc3a4-a258-11e4-8e81-1e8b59593cfe.jpg)

**Comment by tevko** [comment]
very sorry, is the plugin disabled? I'm not seeing it

**Comment by FlorianBrinkmann** [comment]
... I think it was a cache-problem, should work now

**Comment by tevko** [comment]
I see now. What's happening is that theirs no sizes attribute, which means that the browser thinks the image needs to be 100% wide at all times. You should use regex or a filter to put an appropriate sizes attribute on the image tag. We don't do this with the plugin because we have no way of predicting what those sizes will be

**Comment by FlorianBrinkmann** [comment]
okay, thanks for your quick help!
