### ISSUE TITLE
Notice: Use of undefined constant tevkori_filter_post_thumbnail_html

### ISSUE THREAD

**Issue by ivojacobs** [ResponsiveImagesCG/wp-tevko-responsive-images#22]
When in WP_DEBUG mode I get the following error: 
> Notice: Use of undefined constant tevkori_filter_post_thumbnail_html - assumed 'tevkori_filter_post_thumbnail_html' in /sites/domain.tld/www/dev/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 97

changing line 97 in wp-tevko-responsive-images.php from

`add_filter( 'post_thumbnail_html', tevkori_filter_post_thumbnail_html, 0, 5);`

to

`add_filter( 'post_thumbnail_html', 'tevkori_filter_post_thumbnail_html', 0, 5);`

seems to fix the warning... is this correct?

**Comment by tevko** [comment]
yeah, thanks for filing an issue!
