### ISSUE TITLE
Add documentation for the `max_srcset_image_width` filter.

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#225]
In version 3.0 (and in WP 4.4), we added a low-pass filter to the sizes that will be included in `srcset` attributes, which defaults to 1600px, but is filterable using the `max_srcset_image_width` hook ([link](https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/blob/master/wp-tevko-core-functions.php#L154)).

We need to add documentation for this hook with code samples for filtering conditionally based on the width of the original image.

**Comment by jaspermdegroot** [comment]
Landed in 81ab3c8590a2679fc7cab16e92736857d82a34e7
