### ISSUE TITLE
Filters hooked to `tevkori_image_sizes_args` are no longer firing in 3.0.0

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#226]
See [this issue on WP.org](https://wordpress.org/support/topic/firefox-not-loading-in-larger-images-on-resize?replies=5#post-7635000)

**Comment by jaspermdegroot** [comment]
I don't think they never firing, because we have a unit test for this which is passing. I will try to reproduce the issue.

**Comment by joemcgill** [comment]
The unit test assumes we're calling the `tevkori_get_sizes()` function, but that function no longer runs by default after an upgrade to 3.0.0. What we need to do is route any hooks attached to this function to the `wp_calculate_image_sizes()` function instead.

**Comment by jaspermdegroot** [comment]
I see. So the deprecated `tevkori_image_sizes_args` filter should still be applied when the new sizes function runs? I thought it only had to be applied when the deprecated `tevkori_get_sizes()` function is called.
I can create a PR for this.

**Comment by joemcgill** [comment]
That's correct. If someone has a filter applied to the old `tevkori_get_sizes` hook, their function should still affect the `sizes` attribute after upgrading to 3.0
