### ISSUE TITLE
Function to output responsive images in themes

### ISSUE THREAD

**Issue by landwire** [ResponsiveImagesCG/wp-tevko-responsive-images#233]
Hi there,
is there a function I can use to output a responsive image by attachment id in a theme? As far as I understood from this (https://make.wordpress.org/core/2015/09/26/responsive-images-feature-plugin-update-2/) it only filters the content for now, correct?

Thanks,
Sascha

**Comment by joemcgill** [comment]
Hi @landwire,

Any image that you create using `wp_get_attachment_image()` will include `srcset` and `sizes` attributes. You can also build your own image markup using `wp_get_attachment_image_srcset()` and `wp_get_attachment_image_sizes()`.

Cheers,
Joe
