### ISSUE TITLE
Should we increase the default of 'max_srcset_image_width'?

### ISSUE THREAD

**Issue by jaspermdegroot** [ResponsiveImagesCG/wp-tevko-responsive-images#237]
I was thinking that 2048 (twice the default width of image size "large") might be better than the 1600 that we use now.
Of course we should only change it if WP core also wants to change it.

**Comment by joemcgill** [comment]
We decided to let this ride for now. See [the related discussion](https://wordpress.slack.com/archives/feature-respimg/p1447445758000040) in the Slack archives.

We can reopen this ticket if it should become an issue in the future.
