### ISSUE TITLE
Incorrect inline documentation

### ISSUE THREAD

**Issue by jaspermdegroot** [ResponsiveImagesCG/wp-tevko-responsive-images#243]
These are issues in the plugin as well as in WP core trunk.

`wp_get_attachment_image_srcset()`:

- [x] param `$image_meta` missing "Default null"

`wp_calculate_image_srcset()`:

- [x] param `$attachment_id` missing "Default 0"

`wp_calculate_image_srcset`:

- [x] variable `$attachment_id`: add to description " or 0".

`wp_get_attachment_image_sizes()`:

- [x] param `$image_meta` missing "Default null"
- [x] Return description should be "A valid source size value for use in a 'sizes' attribute or false." instead of "A 'srcset' value string or false."

`wp_calculate_image_sizes()`:

- [x] description of the function: "Create 'sizes' attribute value for an image." should be "Creates the 'sizes' attribute value for an image."
- [x] param `$size`: remove " Default 'medium'." since it doesn't have a default
- [x] param `$image_src` should be documented as second instead of fourth
- [x] param `$image_src` missing "Default null" (` = null` is missing in the code as well)
- [x] param `$image_meta` missing "Default null" (` = null` is missing in the code as well)
- [x] param `$attachment_id` missing "Default 0"

`wp_calculate_image_sizes`:

- [x] variable `$size`: remove " Default 'medium'." from description
- [x] variable `$image_src` type should be `string|null` and add to description " or null".
- [x] variable `$image_meta` type should be `array|null` and add to description " or null".
- [x] variable `$attachment_id`: add to description " or 0".

**Comment by joemcgill** [comment]
Closed after manually merging #250

**Comment by joemcgill** [comment]
I've added the changes in 88e8480 to the original ticket in Trac ([#34612](https://core.trac.wordpress.org/ticket/34612#comment:12)) for adding the `wp_calculate_image_sizes()` function.
