### ISSUE TITLE
Test test_tevkori_filter_content_images() failing against WP nightlies

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#251]
Our unit test method, `RICG_Responsive_Images_Tests::test_tevkori_filter_content_images` is failing against Trunk because the fix hasn't been merged into core yet. Once the fix has been applied to core, this should pass as expected.

I'm going to leave this ticket open as a reminder until we've confirmed that all the test are passing.

See: https://core.trac.wordpress.org/ticket/34678

**Comment by joemcgill** [comment]
The changes to core have been made that should fix this issue. 
See: https://core.trac.wordpress.org/changeset/35678

Once we've confirmed that all tests pass in the nightlies tomorrow, this can be closed.

**Comment by jaspermdegroot** [comment]
Confirmed: https://travis-ci.org/ResponsiveImagesCG/wp-tevko-responsive-images/builds/92426311
