### ISSUE TITLE
Image tags without ending slash are never made responsive.

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#259]
See https://core.trac.wordpress.org/ticket/34807.

Looks like we're going to go back to a custom regex for finding images embedded in content, rather than using `get_media_embedded_in_content()`. Let's wait for the ticket in core to resolve and then apply the same update here.

**Comment by joemcgill** [comment]
Fixed in core here: https://core.trac.wordpress.org/changeset/35753

Let's do the same here.

**Comment by jaspermdegroot** [comment]
What shall we do with `tevkori_get_media_embedded_in_content()`? It isn't marked as private function so I suppose we have to deprecate it first before removing it.

**Comment by joemcgill** [comment]
I suppose you're right. I'll move it over to the deprecated functions file and we can remove it in 3.2.

**Comment by joemcgill** [comment]
Fixed in #262
