### ISSUE TITLE
Update documentation about plugin features

### ISSUE THREAD

**Issue by jaspermdegroot** [ResponsiveImagesCG/wp-tevko-responsive-images#265]
Now that WordPress 4.4 has been released I think it's good if we update the documentation in our readme files.
We should explain that the plugin still can be used to include Picturefill and for the advanced image compression. People should also keep using it if you started to use the plugin before version 2.5, because we need to replace `data-sizes` when the `srcset` is already in the markup.
You shouldn't be using the plugin to make images responsive because that means that you are using deprecated functions and/or didn't update to WordPress 4.4 yet.

**Comment by tevko** [comment]
:+1:

**Comment by jaspermdegroot** [comment]
Fixed in https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/768cec8323883c48f5d0498a62420fffe0f5f0d5
