### ISSUE TITLE
Contributors in the readme need to be WP.org usernames

### ISSUE THREAD

**Issue by helenhousandi** [ResponsiveImagesCG/wp-tevko-responsive-images#27]
The author in the main plugin PHP file is an arbitrary string, but contributors listed in the readme are parsed as WordPress.org usernames. We should fix them. The ones I know are:

* Tim Evko: tevko
* Mat Marquis: wilto
* Chris Coyier: chriscoyier
* Kelly Dwan: ryelle
* Andrew Nacin: nacin
* George Stephanis: georgestephanis
* Helen Hou-Sandí: helen
* The Wordpress Core Team: wordpressdotorg

**Comment by joemcgill** [comment]
Joe McGill: joemcgill

**Comment by tevko** [comment]
Done!
