### ISSUE TITLE
Split tevkori_get_src_sizes into tevkori_get_src_sizes_value and tevkori_get_src_sizes

### ISSUE THREAD

**Issue by aFarkas** [ResponsiveImagesCG/wp-tevko-responsive-images#28]
Currently the ``tevkori_get_src_sizes`` function return the srcset value surrounded with ``srcset=""`` attribute.

This makes it hard for developer to work with the actual generated srcset value.

**Comment by tevko** [comment]
We use ``preg_replace`` and some regex to find image tags and add the srcset attribute. I imagine it wouldn't be to difficult to use ``preg_replace`` in the same way, after the plugin has done it's thing. Is there something specifically you're having trouble with?

**Comment by joemcgill** [comment]
+1 This is a good idea.

**Comment by tevko** [comment]
I like this idea as well. Will try to submit a PR shortly

**Comment by tevko** [comment]
Done, feel free to review. Function names also adjusted to reflect spec syntax d7a3b06246be223b205b9d22190bf3789ba6c636

**Comment by joemcgill** [comment]
Looks good, although—thinking out loud—I wonder if it would be beneficial to return `false` if the array is empty?

**Comment by tevko** [comment]
Great point. Will include in next commit
