### ISSUE TITLE
Should we add a line in the readme files encouraging theme developers to add a sizes attribute?

### ISSUE THREAD

**Issue by tevko** [ResponsiveImagesCG/wp-tevko-responsive-images#30]
I think it would only improve the performance of the site. Especially during a case where the browser thinks an image needs full resolution at 100vw, when it really only needs a fraction of that. @Wilto

**Comment by joemcgill** [comment]
I think we may want to revisit the idea of passing an `$args` parameter to the template tag, which could be used by developers for setting the `sizes` attribute along with the `srcset` attribute in their themes. I would imagine something like:

```
tevkori_get_src_sizes( $id, $size, $args );
```

Where `$args` accepts an array like so:

```
$args = array(
  'sizes' => array(
    [0] => array(
      'width' => '100vw',
      'media-query' => 'max-width: 30em',
    ),
    [1] => array(
      'width' => '50vw'
      'media-query' => 'max-width: 50em',
    ),
    [2] => array(
      'width' => 'calc(33vw - 100px)'
    ),
  )
)
```

That would at least give developers who want to declare a sizes attribute a way of doing so.

**Comment by jhned** [comment]
I agree with @joemcgill, that seems like a really easy way to add it in. I've got an idea for how to implement it (plus a couple of other items), so I'll go ahead and try it.

**Comment by tevko** [comment]
@jhned awesome, looking forward to your PR !
