### ISSUE TITLE
Error when downloading / updating plugin

### ISSUE THREAD

**Issue by WesleySmits** [ResponsiveImagesCG/wp-tevko-responsive-images#32]
The latest version 2.0.2 is giving me an error when i tried updating it, i deleted it and i'm getting the same error now when downloading.

Warning: Invalid argument supplied for foreach() in /path/to/site/wp-admin/includes/class-wp-upgrader.php on line 974
The package could not be installed. No valid plugins were found.

**Comment by janhenckens** [comment]
Looks like something went wrong getting the last update in SVN, the plugin files appear to be in trunk/ instead of in the root of the plugin.

**Comment by tevko** [comment]
Looking into this, if it's just an svn issue it'll be fixed shortly. In the mean time, you can copy the files from this repo

**Comment by tevko** [comment]
This has been fixed, everything should be good to go. May require a manual removal + reinstall, but this won't effect any previous images that have been altered by the plugin
