### ISSUE TITLE
Clear Code / Clear Commenting / Clear Word Choice

### ISSUE THREAD

**Issue by jhned** [ResponsiveImagesCG/wp-tevko-responsive-images#33]
This is more of a suggestion than anything else: when we're discussing different pieces of the plugin, it's pretty easy to get confused when we use generic phrases to describe something more specific. For instance, use of the word "sizes" can have two connotations here: 

1. The `sizes` attribute
2. WordPress image sizes

To that end, it might be worth setting up a small glossary of terms to help everybody stay on the same page, otherwise it takes a bit more time to decipher what exactly is being discussed. 

Another small item is just making sure that the code and comments are clearly understandable. For example, line 79 of the main file is commented as `extend image tag to include sizes attribute`, when it probably ought to say `srcset` attribute.

Making our code clear, our comments clear, and our word choice clear will help anyone else who comes along to contribute get up to speed without relying overmuch on reading comprehension.

**Comment by joemcgill** [comment]
Great idea. If you read through the spec posted at whatwg.org (https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element), there are many glossary terms we could just grab directly from there in order to maintain consistency.

**Comment by tevko** [comment]
I completely agree

**Comment by joemcgill** [comment]
Anyone still interested in creating a "glossary" section in the docs for this or are we content with being intentional about using language from WordPress core along with the latest [responsive images spec](https://html.spec.whatwg.org/multipage/embedded-content.html#embedded-content)?

**Comment by joemcgill** [comment]
Since nobody's jumping at the idea, let's at least punt to a future release and keep the conversation going.

**Comment by joemcgill** [comment]
I think we've gotten to a place where we can call this one done. If there are any objections, feel free to comment.
