### ISSUE TITLE
Add picturefill to top not bottom

### ISSUE THREAD

**Issue by aFarkas** [ResponsiveImagesCG/wp-tevko-responsive-images#36]
Currently picturefill is added to the bottom of the page. It would be much better to add the script in the head.

From my viewpoint there are two best practice possibilities to add picturefill to a document:

1. conditionally **before** any blocking stylesheets and javascripts
```html
<script>
(function(d) {
    if(!window.HTMLPictureElement){
        var p = d.createElement('script');
        p.src = 'picturefill.js';
        var s = d.getElementsByTagName('script')[0]; s.parentNode.insertBefore(p, s);
    }
})(document);
</script>
<!--
your stylesheets...
<link href="" />
-->
```
2. Include somewhere in the head after stylesheets using the ``async``  attribute

```html
<!--
your stylesheets...
<link href="" />
-->
<script src="picturefill.js" async=""></script>
```

While both things are possible with wordpress, there is no official API to do this. I'm not sure, wether it is a good "wordpress" practice to add scripts without using the official APIs (in case there is a better embed techique for the special script).

In case you want / should / must use the wordpress functions to add new scripts, please add picturefill simply to the head:

```php
wp_enqueue_script( 'picturefill', plugins_url( 'js/picturefill.js', __FILE__ ), array(), '2.2.0', false);
```

**Comment by joemcgill** [comment]
Good suggestion. I think it's probably wise to stick with the API on this, though it would be really nice if there were a non-hacky way to ad the async attribute via `wp_enqueue_script()`.

**Comment by jhned** [comment]
We actually just worked on this last week-- we may be able to use this filter to update the tag:

`apply_filters( 'script_loader_tag', $tag, $handle, $src );`

[Source on Trac](https://core.trac.wordpress.org/browser/tags/4.1/src/wp-includes/class.wp-scripts.php#L154)

**Comment by tevko** [comment]
I was actually doing the async / header thing first, but as per an earlier slack discussion with Andrew Nacin, the preferred way is to output in the footer using ``wp_enqueue_script()``

**Comment by aFarkas** [comment]
@tevko 
Can you provide some insides here. Because picturefilling is a little bit different from normal script embedding. 

Here is a small quote from Steve Souders, which illustrates the problem:

> I used to say, “JS and CSS are the most important bytes in the page”.

> A few months ago I realized that wasn’t true. Images are the most important bytes in the page.

> My focus on JS and CSS was largely motivated by the desire to get the images downloaded as soon as possible. Users see images. They don’t see JS...

Well in case of picturefill, picturefill is not simply some JS behavior, that isn't seen by the user. Picturefill makes those important images available.

**Comment by tevko** [comment]
I agree that the site will perform better when picturefill is loaded first.
However, that change should be left up to theme developers. Normally I
wouldn't care, but we'd like to get this plugin merged into core, and that
means we have to comply with wp standards

**Comment by aFarkas** [comment]
Can you give me some information or point me to the right direction, how I as a plugin developer can move picturefill to top without moving other core scripts to top and not changing this or other core scripts directly. 

But still don't get, why wp standard enforces scripts to be added in a way, that hurts performance.

**Comment by joemcgill** [comment]
Hey @aFarkas,

Try throwing this in your `functions.php` file to load picturefill in the <head> and add an `async` attribute:

```
function replace_picturefill() {
		remove_action( 'wp_enqueue_scripts', 'tevkori_get_picturefill' );
		wp_enqueue_script( 'picturefill', plugins_url( '/ricg-responsive-images/js/picturefill.js'), array(), '2.2.0', false );
		add_filter('script_loader_tag', 'async_scripts', 10, 3);
}
add_action('wp_enqueue_scripts', 'replace_picturefill', 9);

function async_scripts($tag, $handle, $src) {
	if ('picturefill' === $handle) {
			$tag = str_replace('></', 'async=""></', $tag );
	}

	return $tag;
}
add_filter('script_loader_tag', 'async_scripts', 10, 3);
```

One note: if this assumes you've downloaded the plugin from the WordPress plugins repo. If you've cloned it from GitHub, on the third line you would need to replace "ricg-responsive-images/js/picturefill.js" with "wp-tevko-responsive-images/js/picturefill.js".

**Comment by aFarkas** [comment]
@joemcgill 
Thank you this is very helpful. Maybe my only change would be to include my own picturefill version, so that I have no assumptions where this installed.

**Comment by casey6** [comment]
I understand the case for leaving it up to theme developers. However there's a pretty valid need for having the script in the head. And in fact that is the [intended way of implementing Picturefill](http://scottjehl.github.io/picturefill/#getting-started). The only way, actually. The script was always intended to be in the head, not in the footer.

I have to think in a situation as critical as this, that the intended use of the feature would outweigh the default way on enqueuing scripts in WordPress. Right?

**Comment by peterwilsoncc** [comment]
@aFarkas if you wish to avoid maintaining your own copy of picturefill, this works too for `replace_picturefill`.

        function replace_picturefill() {
                global $wp_scripts;
                $wp_scripts->add_data( 'picturefill',  'group', 0 ); // group 0, HTML header
                add_filter('script_loader_tag', 'async_scripts', 10, 3);
        }
        add_action('wp_enqueue_scripts', 'replace_picturefill', 9);
