### ISSUE TITLE
editor_max_image_size needs to be removed when image is updated in editor

### ISSUE THREAD

**Issue by tevko** [ResponsiveImagesCG/wp-tevko-responsive-images#37]
The editor_max_image_size filter is only removed when an image is uploaded. Updating an image in the editor causes the srcset attribute to be recalculated via javascript, but the w descriptor can sometimes be incorrect because the editor_max_image_size filter still exists in this case. I suggest removing this filter entirely at the start of the plugin. @helenhousandi  would this be a bad thing to do?

**Comment by drrobotnik** [comment]
Not sure the steps your going through, but if tevkori_extend_image_tag is fired when you update, you could pass the width, height attributes into your tevkori_editor_image_size filter so that it is using real sizes.

**Comment by joemcgill** [comment]
@tevko can you add steps to reproduce this bug?

**Comment by tevko** [comment]
After adding a full sized image in the editor:

1.) view srcset value and w attributes
2.) select image you've just added, and change the requested size to a smaller size
3.) view srcset value and w attributes, w attributes can be incorrect

**Comment by joemcgill** [comment]
I think the issue was the result of some false negatives in the way I was estimating source candidates. I believe the pull request above resolves this issue.
