### ISSUE TITLE
Not compatible with jetpack

### ISSUE THREAD

**Issue by tevko** [ResponsiveImagesCG/wp-tevko-responsive-images#46]
https://wordpress.org/support/topic/jetpack-photon-compatibility

**Comment by lmartins** [comment]
Looking forward for this release too. Thanks.

**Comment by joemcgill** [comment]
Looks like there are two different cases we need to be aware of with Jetpack's Photon module:

**Content images:** Photon doesn't affect images being added to content, but instead adds a filter to `the_content` that finds all images in a post and swaps out the src attribute for the photon url when they are displayed on the front end. (FWIW, the code for that filter is pretty nice and could be useful when we filter `sizes` attributes in the content).

**Template images:** When we're building image tags on the front end—for a featured image or any other manually generated image tag—Photon [is filtering](https://github.com/Automattic/jetpack/blob/master/class.photon.php#L359) `image_downsize()`, which is what `wp_get_attachment_image_src()` uses to return an array containing the url, width, and height of an image. We use the width and height information to determine srcset candidates. However, Photon's filter returns a string containing only the url and not the height and width attributes that we need. We could shim this on our end, which is what the suggested patch from the support forum linked above does, but ultimately I think this is a bug with Photon and we should reach out to them with a fix for their filter.

**Comment by tevko** [comment]
@joemcgill agreed. Let's raise an issue in slack tomorrow

**Comment by joemcgill** [comment]
After talking this through with the JetPack team, they are intentionally returning falsey values for height and width and they're not likely to fix this. Additionally, they're handling a lot of the optimizations that we are providing on their end, so we really don't need to worry about adding support for Photon in `srcset` attributes. For those reasons I think we can close this issue.

**Comment by lmartins** [comment]
Thanks for the info Joe, but just to make this clear, does Photon makes this plugin redundant and they should not be used in conjunction?

**Comment by joemcgill** [comment]
In some ways, it seems that way, yes. In the mean time, I wouldn't recommend using them together since Photon is generating optimized image sizes for you on the fly. I'll keep my eye on this issue and will update it with any best practices we learn.
