### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by tevko** [ResponsiveImagesCG/wp-tevko-responsive-images#47]
... tutorials, examples, and some sort of support line, should be linked to the readme file

**Comment by digiltd** [comment]
Not quite "documentation" but a comprehensive look at the plugin from Smashing Magazine

http://www.smashingmagazine.com/2015/02/24/ricg-responsive-images-for-wordpress/

**Comment by joemcgill** [comment]
Fixed in dcd0f69, 4b45022, and 7bdb0db. We can open specific tickets for other doc improvements.
