### ISSUE TITLE
Update "LargestSizeNeeded" clause

### ISSUE THREAD

**Issue by tevko** [ResponsiveImagesCG/wp-tevko-responsive-images#50]
When a theme developer is using the function to get a srcset attribute, they need to use the following markup ``<img src="pathToImage" <?php echo tevkori_get_srcset_string( TheIdOfYourImage, theLargestImageSizeNeeded ); ?> />``

That second parameter doesn't make sense in this case because it's only the media uploader that needs sizing information. The developer is then lead to believe that the second parameter will return a srcset attribute containing only the image sizes at/under what is specified in the second parameter. 

The plugin should be modified so that if the second parameter is left blank, a full srcset attribute is still returned. Then, the docs should be updated.

**Comment by joemcgill** [comment]
Functionally, we use the second parameter as a way to identify the original size, from which we determine our candidate sizes so I think it's just a matter of updating the documentation to be more clear. 

Something like:

## Default usage

```
<img src="pathToImage" <?php echo tevkori_get_srcset_string( 10, 'medium' ); ?> />
```

## Parameters

*$id* (integer) (required) Attachment ID

*$size (string) (optional) Size of the image used as the default `src` attribute: either a string keyword (thumbnail, medium, large, or full), or a 2-item array representing width and height in pixels, e.g., array(32,32). (Default: thumbnail).

**Comment by tevko** [comment]
@joemcgill this can be closed out right?

**Comment by joemcgill** [comment]
I think a change to the readme file that makes this clearer would be a nice resolution to this issue.

**Comment by tevko** [comment]
Being that this is part of 2.2, I'll do a sweeping change when it comes time to release the next version
