### ISSUE TITLE
Broken Images with HTTP & Size Suffixes

### ISSUE THREAD

**Issue by clicknathan** [ResponsiveImagesCG/wp-tevko-responsive-images#57]
After installing and activating this plugin I found the following:

http vs. https settings weren't being respected, so an image would get src="https://whatever.jpg" but then sourceset="http://whatever.jpg", which gives off scary warnings in browsers.

Also, featured images that used, say, the_post_thumbnail('large') would output featured-image-920x450-920x450.jpg instead of just featured-image-920x450.jpg

**Comment by tevko** [comment]
hey @clicknathan would you be able to paste in some code demonstrating the issues you're seeing?

**Comment by clicknathan** [comment]
Sure! The 920x450 being added twice I figured out was not an issue with the plugin, but with my CDN and caching, so that is not an actual issue.

Regarding HTTPS, here's the output on a single blog post page's Featured Image:

<img width="920" height="616" src="https://wandrlymagazine.com/wp-content/uploads/2015/02/DSC08242-920x616-920x616.jpg" srcset="http://wandrlymagazine.com/wp-content/uploads/2015/02/DSC08242-920x616-420x281.jpg 420w, http://wandrlymagazine.com/wp-content/uploads/2015/02/DSC08242-920x616-920x616.jpg 920w, http://wandrlymagazine.com/wp-content/uploads/2015/02/DSC08242-920x616.jpg 920w" class="attachment-large wp-post-image" alt="a hitchhiker wanders through an amusement park">

Which I'm just calling with the_post_thumbnail('large'); in a /inc/content-partial.php file that is in turn called via get_template_part( 'assets/inc/content-partial' ); in single.php (if that would in any way matter, can't imagine why it would).

On lines 75-86 of wp-tevko-responsive-images.php I was trying to change this to:

    	// Loop through each size we know should exist
	foreach( $default_sizes as $key => $size ) {

	  // Reference the size directly by it's pixel dimension
	  $image_src = wp_get_attachment_image_src( $id, $key );
	  if(strpos($image_src[0], 'http:') === 0) {
	    	return str_replace('http:', '', $image_src);
	  }		
	   $arr[] = $image_src[0] . ' ' . $size['width'] .'w';
	}

	return $arr;

But my PHP is not good enough and alas, I'm coming up short.

**Comment by clicknathan** [comment]
Wait, just saw that `return` in there, this seems to be working for me:

    	// Loop through each size we know should exist
	foreach( $default_sizes as $key => $size ) {

		// Reference the size directly by it's pixel dimension
		$image_src = wp_get_attachment_image_src( $id, $key );
		if(strpos($image_src[0], 'http:') === 0) {
	    	$image_src = str_replace('http:', '', $image_src);
	    }		
	    $arr[] = $image_src[0] . ' ' . $size['width'] .'w';
	}

	return $arr;

**Comment by joemcgill** [comment]
Hi @clicknathan,

Could you tell me if your site url is set using an http:// or https:// scheme? In other words, when you look in your admin under Settings > General, is the WordPress Address for your site using HTTPS?

Thanks,
Joe

**Comment by clicknathan** [comment]
I do have http, not https. Probably the issue?

**Comment by joemcgill** [comment]
It's possible. There are many internal functions in WordPress that build your image URLs based on your site url settings. This should be improved in the next version of WP, but for now you may want to try switching to HTTPS if you have a valid certificate and see if that fixes it.

**Comment by joemcgill** [comment]
Hi @clicknathan – were you ever able to see if changing your `site_url` resolved your issue?

**Comment by tevko** [comment]
Closing, @clicknathan feel free to open a new issue if you find anything strange

**Comment by joemcgill** [comment]
Related: https://wordpress.org/support/topic/broken-images-in-chrome
