### ISSUE TITLE
Srcset string always returns full set of sizes

### ISSUE THREAD

**Issue by timrourke** [ResponsiveImagesCG/wp-tevko-responsive-images#62]
Hello, love this plugin. Has simplified my life immensely.

I've noticed that using tevkori_get_srcset_string() always returns a full set of sizes, even when I supply it with a valid name for an available image size to limit the srcset output to be under a particular size. Any thoughts on what might be causing this issue, or is this expected behavior?

Here are the relevant functions I use to generate my image tags. (Note that the initial src for the image comes from a function call to Types, my custom post type/custom field management plugin.)

```
//helper function to retrieve an image's post ID from its src
function get_attachment_id_from_src($image_src) {
	global $wpdb;
	$query = "SELECT ID FROM {$wpdb->posts} WHERE guid='$image_src'";
	$id = $wpdb->get_var($query);
	return $id;
}

//function that I invoke to embed a responsive image in my templates
function tim_rourke_types_responsive( $post_id, $customfieldname, $size, $class = '' ) {
	$imgSrc = types_render_field( $customfieldname, array( 'id' => $post_id, 'output' => 'raw' ) );
	$imgID = get_attachment_id_from_src( $imgSrc );
	$srcSetString = tevkori_get_srcset_string( $imgID, $size );
	$alt = get_post_meta($imgID, '_wp_attachment_image_alt', true);
	return '<img class="' . $class . '" src="' . $imgSrc . '" ' . $srcSetString . ' alt="' . $alt . '" />';
}
```

So if I call the function with the following parameters, and the 'medium' image size is set to 640px wide:

```
echo tim_rourke_types_responsive( get_the_ID(), 'website-mobile-image', 'medium', 'website__image-mobile' );
```

This is the resulting srcset string I see, WAY more than I bargained for:

```
<img class="website__image-desktop" src="http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop.jpg" srcset="http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop-320x770.jpg 320w, http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop-640x1540.jpg 640w, http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop-1024x2463.jpg 1024w, http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop-1280x3079.jpg 1280w, http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop-1600x3849.jpg 1600w, http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop-2000x4811.jpg 2000w, http://timrourke.tim/wp-content/uploads/2015/03/GOAL-screenshot-home-desktop.jpg 2716w" alt="GOAL Project - screenshot of home page in desktop view">
```

Thanks for your thoughts!

**Comment by joemcgill** [comment]
Hey Tim,

Glad the plugin is helping you simplify your workflow. The behavior that you're seeing is exactly what is expected, but it's not at all clear in the documentation. The second (i.e. size) parameter passed to the function—in your case 'medium'—is used to determine the aspect ratio of the image, which is compared with all available sizes available in the meta attachment field of the associated image so the browser can choose whichever image size is most appropriate. 

If you know the actual layout size of the image in your theme, you should also add an additional `sizes` property to your image tag which lets the browser know how wide the image is at each breakpoint in your theme. If you're running the latest master branch of this plugin from the GitHub repo, you can take advantage of a new function, `tevkori_get_sizes_string()` to output a default size attribute for the `$id` and `$size` that you pass to the function.

Hope that helps.

**Comment by timrourke** [comment]
Thanks, that really clears things up! Using lazysizes in conjunction with wp-tevko-responsive-images/Picturefill seems to solve the 'sizes' issue much more efficiently, removing the need for an explicit declaration of a maximum reasonable size. 

I would say the docs could definitely be better for this plugin, at least for folks like me who couldn't read PHP to save their lives. :-)

**Comment by joemcgill** [comment]
Totally agree. Sorry for the confusion.
