### ISSUE TITLE
images loading twice

### ISSUE THREAD

**Issue by side777** [ResponsiveImagesCG/wp-tevko-responsive-images#63]
Wouldn't it make sense to remove the src attribute to prevent browsers from loading images twice?

**Comment by tevko** [comment]
Hey @side777 , typically images loading twice means that your browser doesn't natively support responsive images, and the double loading is happening when picturefill starts to do its thing. That being said, I would say it's better to leave the src attribute in, especially for accessibility and semantic use cases

**Comment by joemcgill** [comment]
In many cases, `src` as a fallback is a requirement, however, it would be good to document exactly when you see images load twice so we can report it upstream to the Picturefill team as they find and fix specific browser bugs.

**Comment by side777** [comment]
picturefill adds a src attribute if it's missing. src in a noscript tag would not be acceptable? i came across the idea of removing the src in this article: http://www.smashingmagazine.com/2014/05/12/picturefill-2-0-responsive-images-and-the-perfect-polyfill/

would be perfect if the picturefill team was able to solve this, of course. i experience random double loading when i add the srcset (and the src) later, after document ready, i.e. with lazy loading... it seems random but i'll dig into this deeper...

**Comment by joemcgill** [comment]
Thanks for the feedback @side777 if you figure out a pattern, let us know which browser version and configuration is causing the issue.

**Comment by tevko** [comment]
Gonna go ahead and call this closed. Feel free to open a new issue if you notice anything weird
