### ISSUE TITLE
Add unit tests for plugin JavaScript

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#72]
Add QUnit tests for unit testing wp-tevko-responsive-images.js. Will probably require some refactoring of the the logic in this code to make it testable.

**Comment by jaspermdegroot** [comment]
This is no longer needed if we decide to switch to content filtering.

**Comment by joemcgill** [comment]
As @jaspermdegroot pointed out, this is no longer needed now that we've moved to using a display filter on the content instead of JS on the backend to update `srcset` and `sizes`.

See #177
