### ISSUE TITLE
picturefill.min.js missing

### ISSUE THREAD

**Issue by makkabi** [ResponsiveImagesCG/wp-tevko-responsive-images#75]
Hey,
if you download install the plugin from this source:
https://wordpress.org/plugins/ricg-responsive-images/
...the file picturefill.min.js is missing in the js directory, so it can't be loaded (the scipt source added to the webpage by the plugin points to js/picturefill.min.js) and the plugin won't work if you use a browser that needs it for responsive images. 
Best,
Jonathan

**Comment by tevko** [comment]
Thanks, we're aware and will be pushing out a patch tonight!

**Comment by makkabi** [comment]
Great!
