### ISSUE TITLE
JS: Sizes object doesn't contain all image sizes

### ISSUE THREAD

**Issue by jaspermdegroot** [ResponsiveImagesCG/wp-tevko-responsive-images#80]
The post data sizes object doesn't contain all image sizes, it only contains the sizes that are available in the editor. Sizes that are added with ```add_image_size```, but not made available in the editor with ```image_size_names_choose``` won't end up in the ```srcset```.

The only way I can think of to fix this is to use AJAX so you can use the same PHP functions to create the ```srcset```.

Note: When looking into this be aware of a bug in WordPress core. When switching to "custom size" in the editor you have to set a size with the same aspect ratio of the original image. However, the ```src``` url won't be updated. So if you have a 300x200 image, inserted it as a 150x150 cropped thumbnail, and then switch in the editor to 150x100 custom size, you get 150x150 (distorted) image displayed at size 150x100. That is if you wouldn't use ```srcset``` of course.

**Comment by joemcgill** [comment]
I was looking into this briefly yesterday and I wonder if this has always been the case or if this changed with the overhaul to wp.media that was done in version 4.2. Need to dig into it a bit more and see if we can get WP to expose that data. In the mean time, we may have to add our own AJAX callback, as you suggest.

**Comment by jaspermdegroot** [comment]
@joemcgill - I first noticed the issue with WP 4.1.

**Comment by joemcgill** [comment]
@jaspermdegroot when you have a moment, you mind testing #102 against this bug and see if it takes care of the issue you were seeing?

**Comment by jaspermdegroot** [comment]
@joemcgill - Sure, I will test it.

**Comment by jaspermdegroot** [comment]
@joemcgill - Your PR does solve the problem. Nice work!
