### ISSUE TITLE
TotalCache CDN rewrites do not include srcset

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#88]
The [W3 TotalCache](https://wordpress.org/plugins/w3-total-cache/) plugin has an option to serve assets from a CDN. When that option is enabled, TC rewrites the `src` attribute of images but not any of the sources passed to the `srcset` attribute. We should do some research into how TC is filtering the `src` and see if we can apply the same filtering to the list of source candidates.

See related: https://wordpress.org/support/topic/cdn-support-3?replies=2#post-6872756

**Comment by jaspermdegroot** [comment]
According to the markup provided by the OP of that ticket only the url of the first source in the ```srcset``` is rewritten. So it's not like the W3TC plugin doesn't touch the ```srcset``` at all. Maybe it's better if we contact the author of W3TC to ask if he can fix this problem in his plugin.

**Comment by joemcgill** [comment]
You know, I missed that the first one was rewritten. I wonder what's going on there. It very well may be something that needs to be done on the W3TC side.

**Comment by tevko** [comment]
is this something we are looking to persue?

**Comment by jaspermdegroot** [comment]
W3TC is a popular plugin so I think we should figure out (preferably together with the author of W3TC) what's going wrong here.

**Comment by szepeviktor** [comment]
W3TC is very plugable. Try searching in its source code.

**Comment by szepeviktor** [comment]
Maybe the `w3tc_cdn_url` in `w3-total-cache/lib/W3/Plugin/BrowserCache.php`.

**Comment by jaspermdegroot** [comment]
Actually my last comment didn't make sense because there is nothing we can do to fix this.
So I posted on W3TC support forum to notify the author about the problem (https://wordpress.org/support/topic/cdn-doesnt-rewrite-srcset-urls?replies=1#post-7448963) but there is no reason to keep this ticket open in our issue tracker.

**Comment by joemcgill** [comment]
Looks like this issue is yet to be resolved on W3TCs side per [this support thread](https://wordpress.org/support/topic/cdn-und-srcset?replies=10). I'm reopening as a reminder to reach out to the plugin team to see what can be done about this.

**Comment by jaspermdegroot** [comment]
I did already reach out to the plugin author (https://wordpress.org/support/topic/cdn-doesnt-rewrite-srcset-urls?replies=1#post-7448963) and 6 people already reported that the plugin doesn't work with WP 4.4.1 (https://wordpress.org/plugins/w3-total-cache/). Not sure what else needs to be done here.

**Comment by joemcgill** [comment]
Reached out to the plugin team. Nothing else we can do here.
