### ISSUE TITLE
Compatibility with Visual Composer?

### ISSUE THREAD

**Issue by iandevlin** [ResponsiveImagesCG/wp-tevko-responsive-images#89]
I currently have the unfortunate task of having to work with a purchased Wordpress theme that uses Visual Composer (or Composter as I call it...) and was hoping to use this picturefill plugin to help reduce the mess.

But it doesn't appear to work as I assume that VC must be using its own media uploader or something.

Can you possibly confirm this?

**Comment by tevko** [comment]
Any way you can get us some more info on VC and possible errors, etc?

**Comment by iandevlin** [comment]
[Visual Composer](http://vc.wpbakery.com/)

I can't see any errors, it's just that when I upload an image via VC's "single image" widget, no extra sizes are created, and the code produced has no srcset. I'm pretty sure it's VC's fault and nothing to do with your plugin, I was just making sure.

**Comment by jaspermdegroot** [comment]
We hook into ```image_send_to_editor``` to add the ```srcset``` and ```sizes``` attributes. This action only runs when you use the "Add Media" button in the default editor to insert an image, not when you insert them with the Visual Composer editor. This might be a problem with other page builder plugins as well.

With the way we currently add the attributes to images that are in the post content there is no way we can fix this at our end. Visual Composer doesn't run actions when it inserts media that we could hook into so you would have to change the code to make it work.

If we would decide to switch to content filtering (see https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/83) this would no longer be a problem. I suggest to close this ticket and add this to the list of "pros" of content filtering. I know that many of the popular themes on ThemeForest include Visual Composer so it would be a nice benefit.

**Comment by iandevlin** [comment]
Ok, cool, as I said, I just wanted to verify that this is indeed what it was and not that I was doing something stupid (always likely).

Thanks for the reply.
