### ISSUE TITLE
typo in example

### ISSUE THREAD

**Issue by orionrush** [ResponsiveImagesCG/wp-tevko-responsive-images#90]
Usage Example

    $sources = tevkori_get_srcset_array( 11, 'medium' );

    $srcset = array();
    foreach( $srcset as $source ) {
    if ( false === strpos(' 900w', $source) {
    $srcset[] = $source;
    }
   }

should read 
     `if ( false === strpos(' 900w', $source) ) {`

**Comment by orionrush** [comment]
actually that isn't quite it either, $sources is never used: 

    $srcset = array();
    $srcset = tevkori_get_srcset_array( $attachment->ID, $size );
     foreach( $srcset as $source ) {
         if ( false === strpos(' 900w', $source)) {
            $srcset[] = $source;
        }
    }
    
     <img src="myimg.png" srcset="<?php implode( ', ', $srcset ); ?>" >

This seemed to do the trick . . . .

**Comment by joemcgill** [comment]
Thanks for noticing the typo and making the correction @orionrush. The intent of the usage example was also not clear, as it was meant to be an example of creating a srcset string that omits a specific image—in this case, a 900w image. Pull request #95 addresses both issues by fixing the code and adding an inline comment about the intent of that foreach loop.
