### ISSUE TITLE
Support attachment_image

### ISSUE THREAD

**Issue by tevko** [ResponsiveImagesCG/wp-tevko-responsive-images#91]
https://wordpress.org/support/topic/incompatibility-with-genesis-framework

>I think that's the plugin some of us discussed at WordCamp London. We discussed whether it was likely to be compatible with genesis_get_image, and I said that it probably is because genesis_get_image calls wp_get_attachment_image. But I later looked at the plugin source and it doesn't support images that come from wp_get_attachment_image, only ones that come from get_the_post_thumbnail or hard-coded into the post body. I don't know why.

**Comment by jaspermdegroot** [comment]
Sounds like this would be fixed when merging PR https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/73

**Comment by joemcgill** [comment]
@jaspermdegroot I was thinking the same thing. I'm Planning to do another look through core to see if there are any potential downsides to #73 before merging.
