### ISSUE TITLE
Change the default sizes attribute for images_send_to_editor

### ISSUE THREAD

**Issue by solemone** [ResponsiveImagesCG/wp-tevko-responsive-images#98]
Hi,
is there a way to change the default sizes attributes for images_send_to_editor?  I use fluid images and want to change the sizes attribute for specific pages/templates.

Thanks a lot. 
Ivo

**Comment by joemcgill** [comment]
Hi @solemone, 

The best way to handle this right now is by removing our `tevkori_extend_image_tag ` filter on `image_send_to_editor` and replace it with your own that mimics ours, but passes your own default array to `tevkori_get_sizes()`. Probably not the most elegant, but would get the job done.

**Comment by solemone** [comment]
All right, thank you for the quick reply.
